services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py loaddata fixtures/accounts.json fixtures/categories.json &&
            python manage.py loaddata fixtures/exchange_items.json fixtures/greenpoints.json fixtures/services.json &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: zero_wast
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
