# Generated by Django 5.2.3 on 2025-06-18 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='status',
            field=models.CharField(choices=[('available', 'Доступно'), ('exchanged', 'Обменяно'), ('reserved', 'Зарезервировано')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangeitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='exchange.category'),
        ),
    ]
