# Generated by Django 5.1.11 on 2025-06-30 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_category_exchangeitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='exchange.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='exchangeitem',
            name='description',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='exchangeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exchange_items/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='exchangeitem',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='exchangeitem',
            name='status',
            field=models.CharField(choices=[('available', 'Доступно'), ('exchanged', 'Обменяно'), ('reserved', 'Зарезервировано')], default='available', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='exchangeitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название товара'),
        ),
    ]
