# Generated by Django 5.1.11 on 2025-07-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS-класс иконки или название изображения', max_length=100),
        ),
    ]
